import json
import sys,os,inspect
import matplotlib.pyplot as plt
import numpy as np
import math
from time import sleep
from fastest_util import *
import fastest_lap

# Defining helper funcitons

def check_files(track, track_path, run_data_path):
    return_code = 0

    try:
        # Load track
        fastest_lap.create_track_from_xml(track, track_path)

    except:
        return_code += 1

    try:
        # Loading run data from json
        with open(run_data_path, "r") as f:
            json.load(f)
    
    except:
        return_code += 2

    return return_code

# Defining the path to the nesessery data
track="catalunya"
track_path = "tracks/catalunya_adapted.xml"

run_data_path = "run.json"

# Performing file check, to see if the selected track exists
file_status = check_files(track, track_path, run_data_path)

# 1 or 3 means track xml cant be loaded, which is critical error so abort
if file_status % 2 == 1:
    os.system("clear")
    print(f"CRITICAL ERROR")
    print(f"No track XML file found or Invalid XML file entered")
    print("Please enter a valid one and try again")
    exit()

os.system("clear")

# Loading track
global s
s = fastest_lap.track_download_data(track,"arclength")

print(f"> Default track: {track} ({track_path})")

# Code 0 means all files exists
if file_status == 0:

    # Loading run data
    with open(run_data_path, "r") as f:
        data = json.load(f)

    print(f"> Default run data: {run_data_path}")

# 2 means run data json cant be loaded, the program can continue without it
if file_status == 2:
    print("> No run data json found, you cant use options that require it until one is generated by Optimal laptime simulation")
    data = None


os.system("pause")

while True:
    choices = """
    1. Run optimal laptime simulation
    2. Run circuit pre-proccessor
    3. Show track 
    4. Show optimal laptime graph
    5. Show all velocities graph
    6. Show Total velocity graph
    7. Show true kappa graph
    8. Show average true kappa inverted graph
    9. Print Values
    10. Show 2 car optimal laptime grap
    11. Show list of data
    12. Scale track xml
    """
    print(choices)

    choice = input("What do you want to do >  ")
    print("\n")

    try:
        choice = int(choice)
    except:
        print("\n======================\n\a")
        continue
    
    if choice == 1:
        # Optimal laptime



        print("Additional data required for this option")
        print(f"NOTE: the current track will be used: {track_path}")
        
        while True:
            car_path = input("Enter path for car's xml file: ")

            # Loading data
            try:
                f = open(car_path, "r")
    
            except OSError:
                print("File couldn't be opened, please enter a difrent path")
            else:
                print("Car XML opened succesfully")
                break

        while True:
            print("Enter the name of the output json file")
            print("NOTE: Do not enter the file extention")
            output_name = input(">")

            # Testing validity of filename
            if ["-",".","(", ")"] in output_name:
                print("Invaluid file name, please try again")
                continue

            # Checking if file exists
            try:
                f = open(f"{output_name}.json", "r")

            except OSError:
                print("File name availiable")
                break
            else:
                print("File already exists, please enter a difrent name")

        print("Running optimal laptime simulation, this may take some tiem depending on the size of the track")
        
        try:
            run_optimal_laptime(track, track_path, car_path, 5)
        except:
            print("Something went wrong running the simulation")
            input("Press enter to continue...")
        else:
            print("Optimal laptime simulation complete")
                
    elif choice == 2:
    # Circuit pre-proccessor


        print("Additional data required for this option")
        
        while True:
            right_kml_path = input("Enter path for the track's right kml file: ")

            # Loading data
            try:
                right_kml = open(right_kml_path, "r")
    
            except OSError:
                print("File couldn't be opened, please enter a difrent path")
            else:
                print("Right KML loaded")
                break

        while True:
            left_kml_path = input("Enter path for the track's left kml file: ")

            # Loading data
            try:
                left_kml = open(left_kml_path, "r")
    
            except OSError:
                print("File couldn't be opened, please enter a difrent path")
            else:
                print("Left KML loaded")
                break

        while True:
            print("Enter the name of the output xml file ")
            print("NOTE: Do not enter the file extention")
            output_name = input(">")

            # Testing validity of filename
            if ["-",".","(", ")"] in output_name:
                print("Invaluid file name, please try again")
                continue

            # Checking if file exists
            try:
                f = open(f"{output_name}.xml", "r")

            except OSError:
                print("File name availiable")
                break
            else:
                print("File already exists, please enter a difrent name")

        element_num = input("Enter the number of elements: ")

        print("Running circuit pre-proccessor, this may take some tiem depending on the size of the track")
            
        run_circuit_preproccessor(right_kml, left_kml, output_name, element_num)
        

    elif choice == 3:
        fig =  fastest_lap.plot_track(*fastest_lap.track_coordinates(track))
        plt.plot([1],[2],linewidth=2,color="blue")
        plt.show()

    elif data == None:
        print("This option needs a run data file to be loaded, please run a laptime simulation and try again")
        os.system("pause")
        
    elif choice == 4:
        fastest_lap.plot_optimal_laptime(s, data["chassis.position.x"], data["chassis.position.y"], track, "blue")
        plt.gca().invert_xaxis()
        plt.show()

    elif choice == 5:
    # Velocities graphs

        # Calculate total velocity from velocity x and y
        vel_x = np.array(data["chassis.velocity.x"])
        vel_y = np.array(data["chassis.velocity.y"])
        vel = []
        for i in range(len(vel_x)):
            vel.append(math.sqrt((vel_x[i]**2) + (vel_y[i]**2))) 


        # Testing if total calculated velocities math the length of vel x (and so y)
        if len(vel) == len(data["road.arclength"]):
            print("Value length matches")
            counter = 0
            for i in range(len(vel)):
                if vel[i] - vel_x[i] < 0.5:
                    counter+= 1

            print("Same values:", counter)
            print("All values same:", len(vel)==counter)

        else:
        # If it fails show the velocity data and raise error

            print("\n\nVelocity data:", vel)

            for i in range(len(data["road.arclength"])):
                print(data["road.arclength"][i], "|", vel[i])

            diff = len(vel) - len(data["road.arclength"])
            print(diff)
            raise TypeError

        # Converting total calculated velocity to np array
        vel_np = np.array(vel)


        # Calculating the diffrence between total velocity and velocity x
        vel_diff = []
        for i in range(len(data["road.arclength"])):
            vel_diff.append(abs((vel[i]-vel_x[i])))

        # Converting total calculated velocity to np array
        dif_np = np.array(vel_diff)

        # Setting labels
        plt.title("Speed")
        plt.xlabel("Road arclength")
        plt.ylabel("Velocities")

        # Show total velocity, velocity y and x and the diffrence between total velocity and velocity y
        plt.plot(data["road.arclength"], vel_np, color='purple')
        plt.plot(data["road.arclength"], dif_np, color='orange')
        plt.plot(data["road.arclength"], vel_x, color='red')
        plt.plot(data["road.arclength"], vel_y, color='blue')
        plt.grid()
        plt.show()
    
    elif choice == 6:
    # Total velocity graph



        # Calculate total velocity from velocity x and y
        vel_x = np.array(data["chassis.velocity.x"])
        vel_y = np.array(data["chassis.velocity.y"])
        vel = []
        for i in range(len(vel_x)):
            vel.append(math.sqrt((vel_x[i]**2) + (vel_y[i]**2))) 

        # Converting total calculated velocity to np array
        vel_np = np.array(vel)

        # Setting labels
        plt.title("Speed")
        plt.xlabel("Road arclength")
        plt.ylabel("Velocity")

        plt.plot(data["road.arclength"], vel_np, color='purple')

        plt.grid()
        plt.show()

    elif choice == 7:
    # Average true kappa


        # Computing the average
        avg_kappa_raw = []
        for i in range(len(data["road.arclength"])):
            temp = 0
            temp += data["front-axle.left-tire.true_kappa"][i]
            temp += data["front-axle.right-tire.true_kappa"][i]
            temp += data["rear-axle.left-tire.true_kappa"][i]
            temp += data["rear-axle.right-tire.true_kappa"][i]
            avg_kappa_raw.append(temp/4)

        avg_kappa = np.array(avg_kappa_raw)

        # Setting labels
        plt.title("Average True Kappa")
        plt.xlabel("Road arclength")
        plt.ylabel("A.T.K")

        plt.plot(data["road.arclength"],avg_kappa, color='red')

        plt.grid()
        plt.show()

    elif choice == 8:
    # Average true kappa inverted


        # Computing the average and then inverting it
        avg_true_kappa_raw = []
        for i in range(len(data["road.arclength"])):
            temp = 0
            temp += data["front-axle.left-tire.true_kappa"][i]
            temp += data["front-axle.right-tire.true_kappa"][i]
            temp += data["rear-axle.left-tire.true_kappa"][i]
            temp += data["rear-axle.right-tire.true_kappa"][i]
            avg_true_kappa_raw.append(1/(temp/4))

        avg_true_kappa = np.array(avg_true_kappa_raw)

        # Setting labels
        plt.title("Average True Kappa Inverted")
        plt.xlabel("Road arclength")
        plt.ylabel("A.T.K.I")

        plt.plot(data["road.arclength"],avg_true_kappa, color='red')

        plt.grid()
        plt.show()

    elif choice == 9:
    # Showing user selected data




        # Propmting the user for a data name to show and plot the values 
        value = input("Choose data to show:")
        keys = list(data.keys())
        for arclen in range(len(keys)):
            print(arclen,"->", data[value][arclen])

    elif choice == 10:
        # Optimal lap graph of 2 cars


        print("Additional data required to show this option")
        while True:
            run_data_1_path = input("Enter path for data of the first car: ")
            run_data_2_path = input("Enter path for data of the first car: ")

            # Loading data
            try:
                with open("run_v1_data.json", "r") as f:
                    data_1 = json.load(f)
                with open("run_v2_data.json", "r") as f:
                    data_2 = json.load(f)
            except:
                print("An error occured when loading the provided files, please try again")
            else:
                print("Files loaded succesfully")
                break
            

        time = np.array(data["time"])

        # Show both optimal curves
        x_center, y_center, x_left, y_left, x_right, y_right, theta = fastest_lap.track_coordinates(track)

        fig = plt.figure(figsize=(14,7))
        plt.axis('equal')
        plt.grid(False)
        plt.plot(x_center,y_center,linewidth=0.5,color=(0.5372549019607843, 0.6039215686274509, 0.7215686274509804, 1.0),linestyle=(0, (20, 4)))
        plt.plot(x_left,y_left,linewidth=1,color=(0.5372549019607843, 0.6039215686274509, 0.7215686274509804, 1.0))
        plt.plot(x_right,y_right,linewidth=1,color=(0.5372549019607843, 0.6039215686274509, 0.7215686274509804, 1.0))

        plt.plot(data["chassis.position.x"], data["chassis.position.y"],linewidth=2,color='blue')
        plt.plot(data_1["chassis.position.x"], data_1["chassis.position.y"],linewidth=2,color='red')
        plt.plot(data_2["chassis.position.x"], data_2["chassis.position.y"],linewidth=2,color='orange')

        plt.gca().invert_xaxis()
        plt.show()



    elif choice == 11:
    # Print options

        # Print all options saved in the run json
        for i in range(len(keys)):
            print(i, ") ", keys[i], sep="")

    elif choice == 12:
    # Scale track xml

        # Print all options saved in the run json
        for i in range(len(keys)):
            print(i, ") ", keys[i], sep="")

    else:
        print("Invalid choice, please try again")